language: java
before_install:
- npm install -g bower
sudo: false
cache:
  directories:
  - $HOME/.gradle
  - $HOME/jgiven-html5-report/node_modules
install: "./gradlew --daemon classes"
script:
- "./gradlew --daemon test -DjunitVersion=4.9"
- "./gradlew --daemon test -DjunitVersion=4.10"
- "./gradlew --daemon test -DjunitVersion=4.11"
- "./gradlew --daemon test -DjunitVersion=4.12"
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
after_success:
- test "$TRAVIS_JDK_VERSION" == "oraclejdk7" && test "$TRAVIS_BRANCH" == "master" && test "$TRAVIS_PULL_REQUEST" == "false" && ./gradlew --daemon overallJacocoReport coveralls uploadArchives
- ./gradlew --stop
env:
  global:
  - secure: G7EOz25xYyIzvQwF0eKEgr+0I2S9ZO2xN6BorELeuAVDowYa2B3hJjk4zIRkc1YGWx1CTYvtOEMVVTp9nL93cn18rTNulDMPl5vvBw6t4Ag1BTovUmN2a2y7N1f4N+stmEKHmH2kUZqYSif5vYbK/2044tDtO8nfQ9/va3HxaKs=
  - secure: gAYQw79fJk+zdr8M4F5ZBWKnyA9eXfUbJQ92ucHw8OETNvawE5tqJflMkt2aCy3hTHDQmzMdI6xIGCEk6XUqe9Rydk9gESpUbErHio9FzTwlx5SQJEISOMLEb2ULe2wKn08ZfZkRITY32RUlo/vNIYDuN8xYMHN3vd1z8j97FvE=
